In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

## Create & Read

### 1D Array

In [11]:
arr1 = np.array([1,2,3,4,5,6])

In [12]:
arr1

array([1, 2, 3, 4, 5, 6])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(6,)

In [15]:
arr1.dtype

dtype('int64')

In [16]:
 arr1.ndim

1

In [17]:
arr1.size

6

### 2D Array

In [21]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape #(row, column)

(2, 3)

In [24]:
arr2.dtype

dtype('int64')

In [25]:
arr2.size

6

### 3D Array

In [31]:
arr3=np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]],[[5,3,6],[1,8,6]]])

In [32]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[5, 3, 6],
        [1, 8, 6]]])

In [33]:
arr3.ndim

3

In [34]:
arr3.shape

(3, 2, 3)

In [35]:
arr3.size

18

## Create Random Array

In [36]:
randomArr = np.random.rand(3,2,3)

In [37]:
randomArr

array([[[0.62573073, 0.52232186, 0.06460997],
        [0.44038547, 0.72786089, 0.25617545]],

       [[0.39074283, 0.00413641, 0.41013872],
        [0.76137514, 0.71373761, 0.95838485]],

       [[0.68945535, 0.02584216, 0.71267099],
        [0.44319799, 0.49646724, 0.7543882 ]]])

In [38]:
randomArr.dtype

dtype('float64')

In [40]:
zeroes = np.zeros((3,2,3))

In [41]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
zeroes.ndim

3

In [43]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [44]:
ones =np.ones((3,2,3))

In [45]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [47]:
arr3[0][0]

array([1, 4, 5])

In [1]:
arr3[0:2]

NameError: name 'arr3' is not defined

In [2]:
arr3

NameError: name 'arr3' is not defined

## Update & Delete

In [4]:
import numpy as np

In [6]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [7]:
a1

array([[[0.64919873, 0.98340975],
        [0.14245306, 0.0302809 ],
        [0.41359014, 0.3793561 ]],

       [[0.58085768, 0.27625386],
        [0.04780246, 0.60576616],
        [0.22935648, 0.54478448]]])

In [8]:
a2

array([[[0.26401569, 0.45982365],
        [0.85667961, 0.34472196],
        [0.70660281, 0.64761901]],

       [[0.23088689, 0.05884405],
        [0.41921611, 0.2629823 ],
        [0.61013609, 0.13062419]]])

### Basic Maths Operation

In [9]:
np.add(a1,a2)

array([[[0.91321442, 1.44323339],
        [0.99913268, 0.37500287],
        [1.12019296, 1.02697511]],

       [[0.81174457, 0.3350979 ],
        [0.46701857, 0.86874846],
        [0.83949257, 0.67540867]]])

In [10]:
np.subtract(a1,a2)

array([[[ 0.38518304,  0.5235861 ],
        [-0.71422655, -0.31444106],
        [-0.29301267, -0.26826291]],

       [[ 0.3499708 ,  0.21740981],
        [-0.37141364,  0.34278385],
        [-0.38077961,  0.4141603 ]]])

In [11]:
np.divide(a1,a2)

array([[[2.45893997, 2.13866718],
        [0.16628511, 0.08784153],
        [0.58532196, 0.58577048]],

       [[2.51576732, 4.6946781 ],
        [0.11402822, 2.30344835],
        [0.37591036, 4.17062485]]])

In [12]:
np.multiply(a1,a2)

array([[[0.17139865, 0.45219506],
        [0.12203663, 0.01043849],
        [0.29224396, 0.24567822]],

       [[0.13411242, 0.01625589],
        [0.02003956, 0.15930578],
        [0.13993867, 0.07116203]]])

### Statistical Operations

In [13]:
sqrt =np.sqrt(25)
abs =np.abs(-2)
power =np.power(2,8)
log =np.log(25)
mins =np.min(a1)
maxs =np.max(a2)

In [14]:
sqrt

np.float64(5.0)

In [15]:
abs

np.int64(2)

In [16]:
power

np.int64(256)

In [17]:
log

np.float64(3.2188758248682006)

In [18]:
mins

np.float64(0.030280903336523113)

In [19]:
maxs

np.float64(0.85667961361391)

### Update

In [20]:
arr3=np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]],[[1,4,5],[6,7,4]]])

In [21]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [22]:
arr3[0][0][2]=500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [23]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

### reshape

In [24]:
arr3.shape

(3, 2, 3)

In [25]:
arr3_reshape = arr3.reshape((2,3,3))

In [26]:
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [27]:
arr3_reshape.shape

(2, 3, 3)

### Appending & Inserting

In [30]:
zeroes=np.zeros((3,2,3))

In [32]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
new_array= np.ones((3,2,3))

In [34]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
appd = np.append(zeroes,new_array, axis=0)  #axis 0 =row,  axis 1 =column

In [36]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
inserted = np.insert(zeroes,1 ,new_array, axis=0)

In [38]:
inserted

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

 ### Delete

In [39]:
arr4 = np.random.rand(3,2,3)

In [40]:
arr4

array([[[0.66968191, 0.22414551, 0.94081375],
        [0.56684169, 0.04622878, 0.35386295]],

       [[0.48423291, 0.59521293, 0.29003397],
        [0.35967577, 0.3655131 , 0.68633612]],

       [[0.71296222, 0.40779603, 0.896016  ],
        [0.53963969, 0.50335227, 0.62660878]]])

In [46]:
# delete the array
arr5=np.delete(arr4 , 0 , axis=1)

In [47]:
arr4

array([[[0.66968191, 0.22414551, 0.94081375],
        [0.56684169, 0.04622878, 0.35386295]],

       [[0.48423291, 0.59521293, 0.29003397],
        [0.35967577, 0.3655131 , 0.68633612]],

       [[0.71296222, 0.40779603, 0.896016  ],
        [0.53963969, 0.50335227, 0.62660878]]])

In [48]:
arr5

array([[[0.56684169, 0.04622878, 0.35386295]],

       [[0.35967577, 0.3655131 , 0.68633612]],

       [[0.53963969, 0.50335227, 0.62660878]]])

In [49]:
np.save("new_array", arr5 )

In [51]:
np.load("new_array.npy")

array([[[0.56684169, 0.04622878, 0.35386295]],

       [[0.35967577, 0.3655131 , 0.68633612]],

       [[0.53963969, 0.50335227, 0.62660878]]])